### ISSUE TITLE
Default NPM Scripts are broken

### ISSUE THREAD

**Issue by americkson** [fourkitchens/sous-drupal-project#24]
No longer able to run `npm run X` scripts. Looks like this change removed the references to the scripts.

https://github.com/fourkitchens/sous-drupal-project/commit/600ec91995188c170fab8aa620f9fde84e2f61d8#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by laura-johnson** [comment]
Closing this as I believe it's resolved, we'll open a new ticket if needed.
