### ISSUE TITLE
Can the Entity Browser icon in the WYSIWYG be updated to an icon that hints at "media"?

### ISSUE THREAD

**Issue by amazingrando** [fourkitchens/sous-drupal-project#27]
Currently, the icon in the WYSIWYG for the Entity browser is a big "E". I'd like to see it be an icon that hints at it being "media". I know that Entities aren't always media but I believe this will be the most common use case for site content editors.

I'm happy to provide the icon.

**Comment by americkson** [comment]
Added this to the Drupal.org issue queue: https://www.drupal.org/project/sous/issues/3232923
