### ISSUE TITLE
Composer installation

### ISSUE THREAD

**Issue by ugintl** [fourkitchens/sous-drupal-project#34]
I cloned the repo and run "composer update". Then installed the site using the UI. Everything went well, but the front page is empty. It is as if it is not loading. Then I created a "page" content and when I visit the page, it gives me this
![sous](https://user-images.githubusercontent.com/12570802/128630732-b24c0352-2649-4227-9613-e58aa4868ebe.jpeg)

Do I have to follow some extra steps?

**Comment by ugintl** [comment]
I realized I have to build the theme. So I followed the instrutions here https://docs.emulsify.info/installation/design-system, but still the same.

**Comment by americkson** [comment]
Added this to the drupal.org issue queue. This happened because there was a change to the emulsify install path. We need to adjust the sous install to reflect that change so you do not have to do it manually. 
https://www.drupal.org/project/sous/issues/3232924
