### ISSUE TITLE
White page after installation

### ISSUE THREAD

**Issue by ugintl** [fourkitchens/sous-drupal-project#45]
I installed sous, but I am getting a white page. I saw that composer ran some npm commands as welll. I am using nodejs 14. Is it a problem with my nodejs version? What else do I need?

**Comment by cbfannin** [comment]
After installation, you should end up at a page with instructions on how to log in with user credentials created for you. OOTB Sous has no theming but works well with the Emulsify Design System which creates a custom sub-theme for you that you can enable and start building with.
