### ISSUE TITLE
During installation, replace the frying pan PNG with an SVG

### ISSUE THREAD

**Issue by amazingrando** [fourkitchens/sous-drupal-project#50]
Update the frying pan graphic shown in the screenshot below with a new SVG version. This will make the image crisper on high-definition screens.

<img width="1020" alt="CleanShot 2022-02-08 at 16 03 53@2x" src="https://user-images.githubusercontent.com/409903/153075889-fdc0717f-dadd-4592-a3f5-52807561509f.png">

![cooking 1](https://user-images.githubusercontent.com/409903/153076028-013c5ee5-c587-4ba9-bab4-f7f6a29f926f.svg)

**Comment by laura-johnson** [comment]
There's no frying pan now that we're not using the distro anymore. Closing.
