### ISSUE TITLE
During installation, on "Verify Requirements", add space above "Check messages and try again"

### ISSUE THREAD

**Issue by amazingrando** [fourkitchens/sous-drupal-project#51]
On "Verify Requirements", add a 1rem space above "Check messages and try again", as shown in the following screenshot.

![check the](https://user-images.githubusercontent.com/409903/153076709-160ed92c-5bfe-4988-82d8-bc7f87f1544a.png)

**Comment by laura-johnson** [comment]
Closing this as I believe it's resolved, we'll open a new ticket if needed.
