### ISSUE TITLE
During installation, in the "Configure site" section, update the page title

### ISSUE THREAD

**Issue by amazingrando** [fourkitchens/sous-drupal-project#52]
During installation, in the "Configure site" section, remove the pipe shown in the screenshot below.

![CleanShot 2022-02-08 at 16 06 19@2x](https://user-images.githubusercontent.com/409903/153077120-3d61543a-6e33-4616-a471-911aebc022bc.png)

**Comment by laura-johnson** [comment]
Closing this as I believe it's resolved, we'll open a new ticket if needed.
