### ISSUE TITLE
Scaffolding in project is using drupal-composer/drupal-scaffold definition instead of drupal/core-composer-scaffold

### ISSUE THREAD

**Issue by generalredneck** [fourkitchens/sous-drupal-project#80]
https://github.com/fourkitchens/sous-drupal-project/blob/3b583eeeb8983ad7a07cd014805281f231ea7259/composer.json#L87-L111

**Comment by cbfannin** [comment]
I think this is correct. The definition didn't change, just the packages used for the scaffolding.

Previously the package was `drupal-composer/drupal-scaffold` but now it is `drupal/core-composer-scaffold` and uses the same `drupal-scaffold` definition.
https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold#s-migrating-composer-scaffold

I did do some work on the scaffolding though as the new method no longer uses the "initial" key but rather uses 'file-mapping': https://github.com/fourkitchens/sous-drupal-project/issues/84
