### ISSUE TITLE
Build Bug: error computing cache key: template: cacheKey: executing "cacheKey" error calling checksum: no such file or directory

### ISSUE THREAD

**Issue by cbfannin** [fourkitchens/sous-drupal-project#86]
This error is being reported during Builds on CircleCi. Does not appear to be breaking the build though.
`error computing cache key: template: cacheKey:1:20: executing "cacheKey" at <checksum "~/project/composer.lock">: error calling checksum: open /home/circleci/project/composer.lock: no such file or directory`

**Comment by laura-johnson** [comment]
Closing this as I believe it's resolved, we'll open a new ticket if needed.
